### ISSUE TITLE
request about the meaning of the  'self.uncertainty', thanks a lot

### ISSUE THREAD

**Issue by mengshiyu0109** [PRBonn/LiDAR-MOS#39]
Dear author,

I wanna know that the meaning of the 'self.uncertainty', what does it mean?
I got  confused about that.  It means that it will use the "mean & variance" ?

Thanks !

**Comment by Chen-Xieyuanli** [comment]
Hey @mengshiyu0109, sorry for the late reply. I was on holiday. 
I guess you are talking about the 'self.uncertainty' in our SalsaNext version. It is inherent from the original SalsaNext a flag to use uncertainty with dropout and MCL sampling. For more details, you could find them in the original paper [link](https://arxiv.org/pdf/2003.03653.pdf).
Since it is not the main focus of our method, I will therefore close this issue.

Feel free to reopen it if you still have problems. I would also appreciate it if you could star our repo if you find it useful.
Thanks.
